### ISSUE TITLE
作者您好，不知该插件  支持多人音频会议么？

### ISSUE THREAD

**Issue by seeyou888999** [JiangJuHong/FlutterTencentRtcPlugin#1]

**Comment by JiangJuHong** [comment]
你好，这个插件基于腾讯云RTC，支持一对一和多对多的视频、语音通话。你可在这个基础上实现会议功能。

**Comment by seeyou888999** [comment]
目前该插件 是还没有实现一对一这个功能 是么？ 因为我真机测试 用两台加入同一个房间 是没有显示双方通话的。这个也是需要自己去实现的 。对么?

**Comment by JiangJuHong** [comment]
这个插件目前已经实现了RTC音视频通话，包括一对一、多对多，通过监听器可监听到其它用户加入房间的事件

**Comment by seeyou888999** [comment]
噢。明白了 只是没有进行纹理渲染。 好的 那我去瞅瞅 。

**Comment by JiangJuHong** [comment]
这个插件相当于实现了底层功能，且提供了本地和远端视图，但是没有对UI做处理，UI处理需要根据业务需求在Flutter中实现
