### ISSUE TITLE
iPhone8 plus 10 sdk 13.5编译失败

### ISSUE THREAD

**Issue by dancebear** [JiangJuHong/FlutterTencentRtcPlugin#10]
Undefined symbols for architecture arm64:
  "_vImageConvert_YpCbCrToARGB_GenerateConversion", referenced from:
      +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_vImageRotate90_Planar8", referenced from:
      +[TXCPusherUtil newSampleBufferByRotateNV12_vImage:rotation:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_kvImage_YpCbCrToARGBMatrix_ITU_R_601_4", referenced from:
      +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_vImageConvert_420Yp8_CbCr8ToARGB8888", referenced from:
      +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_vImageRotate90_Planar16U", referenced from:
      +[TXCPusherUtil newSampleBufferByRotateNV12_vImage:rotation:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
![image](https://user-images.githubusercontent.com/1238721/87024644-fa6b8280-c20b-11ea-86d9-820dd87afa04.png)
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by dancebear** [comment]
已解决，添加依赖库 libc++ 、Accelerate.framework即可
![image](https://user-images.githubusercontent.com/1238721/87028177-d199bc00-c210-11ea-9271-048dbacb3ce9.png)

**Comment by JiangJuHong** [comment]
感谢您的互动.
