### ISSUE TITLE
IOS无法运行，错误信息：symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by yhz199132** [JiangJuHong/FlutterTencentRtcPlugin#14]
Undefined symbols for architecture arm64:
      "_vImageConvert_YpCbCrToARGB_GenerateConversion", referenced from:
          +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
      "_vImageRotate90_Planar8", referenced from:
          +[TXCPusherUtil newSampleBufferByRotateNV12_vImage:rotation:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
      "_kvImage_YpCbCrToARGBMatrix_ITU_R_601_4", referenced from:
          +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
      "_vImageConvert_420Yp8_CbCr8ToARGB8888", referenced from:
          +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
      "_vImageRotate90_Planar16U", referenced from:
          +[TXCPusherUtil newSampleBufferByRotateNV12_vImage:rotation:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

cocopods version :1.9.1
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)

**Comment by JiangJuHong** [comment]
请检查您的项目是否支持 swift

**Comment by yhz199132** [comment]
项目是支持swfit的，昨天还能运行，今天开始就不能用了。今天要打包上线的时候，发现ios无法运行了

**Comment by JiangJuHong** [comment]
昨天能用今天不能用？可能是您的项目中出现了一些问题，在此期间该插件没有进行任何升级。

**Comment by yhz199132** [comment]
插件没有升级，不过开始报的是其他错误，让执行“pod repo update",我执行之后就是现在的错误了 

Undefined symbols for architecture arm64:
  "_vImageConvert_YpCbCrToARGB_GenerateConversion", referenced from:
      +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_vImageRotate90_Planar8", referenced from:
      +[TXCPusherUtil newSampleBufferByRotateNV12_vImage:rotation:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_kvImage_YpCbCrToARGBMatrix_ITU_R_601_4", referenced from:
      +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_vImageConvert_420Yp8_CbCr8ToARGB8888", referenced from:
      +[TXCPusherUtil newNV12ToBGRAPixelBuffer:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
  "_vImageRotate90_Planar16U", referenced from:
      +[TXCPusherUtil newSampleBufferByRotateNV12_vImage:rotation:] in TXLiteAVSDK_TRTC(TXCPusherUtil.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JiangJuHong** [comment]
请尝试执行 `flutter clean` `pod install` 等命令

**Comment by yhz199132** [comment]
还是一样的错误。这个是否跟cocopods版本有关？

**Comment by JiangJuHong** [comment]
不排除这种可能性，我并非全职IOS开发人员，对这类问题了解的不是很多

**Comment by JiangJuHong** [comment]
如果没有其它内容，这个问题我将会关闭，在您需要时随时可以重新打开.
