### ISSUE TITLE
setVideoEncoderParam调用传参问题

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#17]
![image](https://user-images.githubusercontent.com/70259290/91276451-26d76000-e7b4-11ea-8115-0a7c1456520b.png)
![image](https://user-images.githubusercontent.com/70259290/91276479-2fc83180-e7b4-11ea-81d3-0db9aaee6825.png)
![image](https://user-images.githubusercontent.com/70259290/91276528-42db0180-e7b4-11ea-96ff-0e3329e3f053.png)
![image](https://user-images.githubusercontent.com/70259290/91276561-4ff7f080-e7b4-11ea-8af9-2f9817d09ecc.png)

参数param传入一个对象，报错。想请教下参数应该怎么传呢

**Comment by JiangJuHong** [comment]
该问题为Dart语法部分，传递map时，可以直接使用键值对，而不用对象包起来，例如：

````
setXXX(
 a:1,
 b:2
);
````

**Comment by shop987** [comment]
![image](https://user-images.githubusercontent.com/70259290/91320045-adf5f980-e7ef-11ea-8142-985320dac76b.png)
直接这样写不行呢

**Comment by JiangJuHong** [comment]
这里传递的不是一个map，是一个实体，你需要创建一个实体:
````
setXXX(
  params: VideoEncoderParam(
   a:1,
   b:2,
   c:3
  )
);
````

**Comment by shop987** [comment]
按照上面方式设置后，dart不报错了。但是java层报错
![image](https://user-images.githubusercontent.com/70259290/91376930-dd891e00-e850-11ea-88c4-0ded1d60e338.png)

**Comment by shop987** [comment]
![image](https://user-images.githubusercontent.com/70259290/91378960-2d1d1900-e854-11ea-9d66-e2b1f9b7c5f4.png)
![image](https://user-images.githubusercontent.com/70259290/91378983-36a68100-e854-11ea-9957-74f9ebec0724.png)
传参形式是这样的，引入了video_enc_param_entity.dart，使用里面的类VideoEncParamEntity

**Comment by JiangJuHong** [comment]
这可能是一个BUG，我将在下一个版本进行修复

**Comment by JiangJuHong** [comment]
这个问题在 `0.1.13` 中被修复.

**Comment by shop987** [comment]
感谢，问题已解决

**Comment by shop987** [comment]
toJson()这个方法是不是没有必要？去掉了我看也能正常运行

**Comment by JiangJuHong** [comment]
理论上来说是这样的，我会将它移除，但是只会随着下一个版本更新而更新
