### ISSUE TITLE
日志问题请教

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#18]
![image](https://user-images.githubusercontent.com/70259290/91678285-c3fd1480-eb77-11ea-8052-1f4cd39e897d.png)
请问下，进入房间就会疯狂打这个日志，这是系统日志还是底层sdk打的日志。把底层sdk的日志关了好像不起作用
![image](https://user-images.githubusercontent.com/70259290/91678377-fd358480-eb77-11ea-9c27-f309505d4cc6.png)

**Comment by JiangJuHong** [comment]
应该是系统日志，例如相机等内容的输出，Rtc的日志关闭后将不会进行输出.

**Comment by shop987** [comment]
系统日志如何关掉呢

**Comment by JiangJuHong** [comment]
这个暂时不清楚，可以查看腾讯云RTC文档或咨询下腾讯云RTC的工单
