### ISSUE TITLE
多个用户进入同一个房间，第一个用户关掉视频后，其他远端用户的视频流显示异常

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#20]
![image](https://user-images.githubusercontent.com/70259290/92238928-bd123100-eeec-11ea-8edb-d8110e243084.png)
![image](https://user-images.githubusercontent.com/70259290/92238996-db782c80-eeec-11ea-930c-d04bf886981d.png)
我这里进入了3个用户，当关掉排在第一个用户的视频后，按理说第二个远端用户的视频应该显示在第一位。但是现在显示异常

**Comment by JiangJuHong** [comment]
dmeo并不完善，请在业务代码中进行测试

**Comment by shop987** [comment]
新版demo这个问题也存在，希望有空可以完善下这里的视频view显示逻辑

**Comment by JiangJuHong** [comment]
此项目非商业项目，dmeo并不完善，请在业务代码中进行相应更改

**Comment by shop987** [comment]
试了几种方式都不太行，所以想看看大佬的解决方式

**Comment by JiangJuHong** [comment]
抱歉，目前我实际线上场景为一对一，暂时没有遇到多对多的场景，所以也没有类似的编码经验

**Comment by c1avie** [comment]
这个问题我也遇到了，感觉是删除第一个视频后，后面视频view的位置发生了变化。导致native view显示异常

**Comment by c1avie** [comment]
这个问题可以给videoView加个key属性就能解决
