### ISSUE TITLE
view api使用的疑惑

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#21]
![image](https://user-images.githubusercontent.com/70259290/92362954-575bba00-f123-11ea-83ff-6d1ba3261ebc.png)

涉及view相关的api可以改造成跟安卓文档类似，api方法都集成在trtcCloud里面。
把承载画面的控件传进去吗

![image](https://user-images.githubusercontent.com/70259290/92363091-8bcf7600-f123-11ea-93cc-5ae65e2063af.png)

**Comment by JiangJuHong** [comment]
由于该插件是基于 Flutter `PlatforView ` 特性， 目前暂时没有办法进行组件传递，感谢您的建议.
