### ISSUE TITLE
请问destroySharedInstance销毁单例这个方法可以加到api里面吗

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#23]
![image](https://user-images.githubusercontent.com/70259290/93088476-85656f00-f6cc-11ea-8868-b96f9febee64.png)

**Comment by JiangJuHong** [comment]
你好，我会检查该SDK版本是否存在该接口，如果存在，我会在近期进行添加（目前琐事比较多，能抽出的时间较少），如果您急用，建议提交PR，我进行打包!

**Comment by JiangJuHong** [comment]
如果没有其它疑问，我将关闭此 Issues，在需要时可以重新打开
