### ISSUE TITLE
有计划实现腾讯的 TRTCCalling 接口么

### ISSUE THREAD

**Issue by JarnTang** [JiangJuHong/FlutterTencentRtcPlugin#24]
TRTCCalling 是基于腾讯云实时音视频（TRTC）和即时通信 IM 服务组合而成的，支持1v1和多人语音通话。

TRTCCalling 是一个开源的 Class，依赖腾讯云的两个闭源 SDK。

[官方介绍文档地址](https://cloud.tencent.com/document/product/647/47761)

**Comment by JiangJuHong** [comment]
抱歉，目前暂无支持计划，如果后续有支持计划，将提取新插件

**Comment by JiangJuHong** [comment]
如果没有其它疑问，我将关闭此 Issues，在需要时可以重新打开
