### ISSUE TITLE
setMixTranscodingConfig的接口传参实现

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#25]
![image](https://user-images.githubusercontent.com/70259290/93350472-47eb1800-f86b-11ea-834c-3b8e0f6b5f0f.png)
请教下这种TRTCTranscodingConfig类中又定义了一个 TRTCMixUser类，这种参数该怎么传呢。videoEncoder那种可以jsonEncode，java层再jsonParse。这种复杂的数据结构好像不行

**Comment by JiangJuHong** [comment]
可以的，复杂结构也可以序列化为json，然后在 java/swift 通过json反序列化

**Comment by JiangJuHong** [comment]
如果没有其它疑问，我将关闭此 Issues，在需要时可以重新打开
