### ISSUE TITLE
Bitmap图片对象flutter层怎么传过去比较好？

### ISSUE THREAD

**Issue by shop987** [JiangJuHong/FlutterTencentRtcPlugin#26]
![image](https://user-images.githubusercontent.com/70259290/93841388-02dd4080-fcc6-11ea-968b-b9eb9bcdc1dd.png)

请教下想用到这个接口，接口接收的是一个Bitmap对象。flutter层怎么传过去比较好呢，有什么比较好的方案吗

**Comment by JiangJuHong** [comment]
建议在flutter层传递路径，然后在android/ios将文件转换为 Bitmap

**Comment by shop987** [comment]
那图片是直接放在sd卡里面吗，还是可以放到flutter项目目录里

**Comment by JiangJuHong** [comment]
建议存放在 flutter 的 assets，然后在使用时进行如下步骤：
````
1. 检测sd卡目录中是否存在该资源文件
    1.1 如果不存在，则进行拷贝
2. 传递该资源文件的路径
````
以上步骤均为flutter层操作

**Comment by shop987** [comment]
好的谢谢，我试一下

**Comment by JiangJuHong** [comment]
参考拷贝代码:
````dart
    int lastIndex = assets.lastIndexOf("/");

    // 初始化目录
    final dir = await getApplicationDocumentsDirectory();
    Directory rootDir = new Directory("${dir.path}${lastIndex != -1 ? "/${assets.substring(0, lastIndex)}" : ""}");
    if (!(await rootDir.exists())) {
      await rootDir.create(recursive: true);
    }

    // 初始化文件
    final file = new File("${rootDir.path}${lastIndex == -1 ? assets : assets.substring(lastIndex)}");
    if (!(await file.exists())) {
      final soundData = await rootBundle.load(assets);
      final bytes = soundData.buffer.asUint8List();
      await file.writeAsBytes(bytes, flush: true);
    }
````

**Comment by shop987** [comment]
这个拷贝代码是 把flutter assets中的图片拷贝到sd卡目录，然后再把路径传过去是吧。flutter assets不能直接获取到图片路径吗

**Comment by JiangJuHong** [comment]
对的

**Comment by shop987** [comment]
![image](https://user-images.githubusercontent.com/70259290/95537381-2cb19980-0a20-11eb-9368-35e5f3fb2100.png)


这种方案可行吗，是不是比写文件的方式高效一些

**Comment by JiangJuHong** [comment]
Rtc插件升级到 1.0.0，已支持个人版几乎所有接口。内部代码有对 Bitmap 参数进行处理，请参考： 文档资源中的 setVideoMuteImage 接口

**Comment by JiangJuHong** [comment]
> ![image](https://user-images.githubusercontent.com/70259290/95537381-2cb19980-0a20-11eb-9368-35e5f3fb2100.png)
> 
> 这种方案可行吗，是不是比写文件的方式高效一些

不确定是否更高效，但是对资源占用更小，这是一种友好的方式，或许后期我将会对插件内部进行修改。感谢您的建议。

**Comment by shop987** [comment]
好的。
![image](https://user-images.githubusercontent.com/70259290/95540908-8f0c9900-0a24-11eb-8f42-f31a3f60ebf2.png)
这里是不是有点问题，AssetImage('icons/heart.png')， 这里传入的应该是AssetImage对象，不是一个String
吧？

**Comment by JiangJuHong** [comment]
不需要传递 AssetImage 对象，只需要传递具体的资源路径即可。
