### ISSUE TITLE
8/android/src/main/java/top/huic/tencent_rtc_plugin/view/TencentRtcVideoPlatformView.java:10: 错误: 找不到符号 import androidx.annotation.NonNull;

### ISSUE THREAD

**Issue by neo693** [JiangJuHong/FlutterTencentRtcPlugin#3]
`The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.`

大佬你好，请问这个怎么解决

**Comment by JiangJuHong** [comment]
用 Android Studio 打开Android目录，请确保Gradle Sync运行正常，如果出现异常，请尝试配置代理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Simons <notifications@github.com&gt;
发送时间: 2020年5月1日 16:15
收件人: JiangJuHong/FlutterTencentRtcPlugin <FlutterTencentRtcPlugin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentRtcPlugin] 8/android/src/main/java/top/huic/tencent_rtc_plugin/view/TencentRtcVideoPlatformView.java:10: 错误: 找不到符号 import androidx.annotation.NonNull; (#3)

**Comment by neo693** [comment]
[https://github.com/flutter/flutter/issues/23995](url) 搞了一天没搞定 查不到解决方案  😭

**Comment by neo693** [comment]
安卓的问题解决了 这个可以关了 大佬
