### ISSUE TITLE
进房退房，如果视频view size宽高发生了变化，视频view会出现闪动。

### ISSUE THREAD

**Issue by c1avie** [JiangJuHong/FlutterTencentRtcPlugin#30]
这个问题不知道有没有好的解决办法

**Comment by JiangJuHong** [comment]
目前针对这个我还没有比较好的解决方案，可能是刷新状态导致的这个问题。

**Comment by c1avie** [comment]
比如进入一个远端用户，屏幕变成上下双屏。试了Container size变化的话不会有这个问题，像是platformView的问题

**Comment by c1avie** [comment]
试了IOS view没有这个问题，安卓这边我再看看优化措施
