### ISSUE TITLE
setVideoEncoderParam 无法使用，导致crash

### ISSUE THREAD

**Issue by yankunren** [JiangJuHong/FlutterTencentRtcPlugin#31]

**Comment by JiangJuHong** [comment]
请详细描述 "setVideoEncoderParam" 具体无法使用场景

**Comment by yankunren** [comment]
在提供的demo中，多人视频会议，进入房间前设置视频参数，进入房间 app crash

环境：
```
flutter 1.22.2
iOS14
```

![image](https://user-images.githubusercontent.com/1218165/96893463-4d1c3200-14bd-11eb-8bd7-5231b29cfe6b.png)

**Comment by JiangJuHong** [comment]
请提供设备信息，并且是否有崩溃日志信息，这有便于排查

**Comment by yankunren** [comment]
> 请提供设备信息，并且是否有崩溃日志信息，这有便于排查

iPhone 7/8 plus
ios 14.0.1

没有捕捉到log，crash后直接断开连接

**Comment by JiangJuHong** [comment]
好的，我尝试一下，修改后我会更新isses

**Comment by JiangJuHong** [comment]
这个问题在 `1.0.2` 中被解决.

**Comment by yankunren** [comment]
> 这个问题在 `1.0.2` 中被解决.

谢谢

**Comment by JiangJuHong** [comment]
推荐您加入QQ群共同讨论： 850923396
