### ISSUE TITLE
remoteView 不显示

### ISSUE THREAD

**Issue by neo693** [JiangJuHong/FlutterTencentRtcPlugin#4]
日志显示开始观看 ，但无画面显示 ，没有任何报错，麻烦大佬有空看一下

**Comment by neo693** [comment]
能否加下大佬微信，有偿咨询

**Comment by neo693** [comment]
startRemoteSubStreamView    可能是这个方法没有支持的原因

**Comment by JiangJuHong** [comment]
日志有错误信息输出吗？你的设备是什么？使用的demo还是集成到项目中呢？

**Comment by neo693** [comment]
> 日志有错误信息输出吗？你的设备是什么？使用的demo还是集成到项目中呢？

搞定了，因为我播放的是辅流，但是sdk没支持startRemoteSubStreamView这个方法，我自己添加了一下就可以了

**Comment by see-sea** [comment]
兄弟，SDK是不是因为比较旧？
