### ISSUE TITLE
pk和美颜功能有进度吗

### ISSUE THREAD

**Issue by Laipt** [JiangJuHong/FlutterTencentRtcPlugin#8]
PK和美颜功能有计划什么时候更吗

**Comment by JiangJuHong** [comment]
你好，由于工作原因，暂时不确定该功能具体更新时间，如果您迫切使用，可以根据原先代码进行编写（实际上非常简单，依葫芦画瓢）。如果您编写完成后，请求您提供PR，非常感谢。

**Comment by bishen** [comment]
SDK自带的美颜功能有点鸡肋

**Comment by JiangJuHong** [comment]
FlutterTencentPlugin 升级到 v1.0.0
* 升级最新版SDK
* 增加几乎所有接口
* 重新更改Demo
